### ISSUE TITLE
var wrapping

### ISSUE THREAD

**Issue by allanbowe** [macropeople/sasjs-cli#125]
In the `sasjsconfig` file we add variables in the following way:

```
            "tgtBuildVars": {
                "DCPATH":"/tmp/dc",
                "ADMIN":"All Users"
                },
```

The problem is that there are SAS systems out there that have line length limits for programs as low as 256 chars.  This causes wrapping for long variables.

We need a mechanism to wrap macro variables to a max-width of, say, 200 chars.

So if we have a variable like this:

```
            "tgtBuildVars": {
                "example":"lets pretend this is over 200 chars long for demo purposes etc etc etc"
                },
```

Becomes:
```
%let example=lets pretend this is over%trim(
) 200 chars long for demo purposes e%trim(
)tc etc etc;
```
The `%trim()` function in SAS will compress out the blanks / carriage returns and make the variable appear as one long string.

**Comment by krishna-acondy** [comment]
Fixed by https://github.com/macropeople/sasjs-cli/commit/28252ad1262d808dae032c9481a0ab62c7a7e02c.
