### ISSUE TITLE
ignore assets without file.extension format

### ISSUE THREAD

**Issue by allanbowe** [macropeople/sasjs-cli#127]
each asset in the web compilation should have a body and an extension

This should prevent hidden files being compiled (eg below)

![image](https://user-images.githubusercontent.com/4420615/82557764-a4178700-9b6c-11ea-98a5-ba1197791153.png)

**Comment by krishna-acondy** [comment]
Fixed by https://github.com/macropeople/sasjs-cli/commit/0a84621ed85998972102337d047b6c22102beb5e.
