### ISSUE TITLE
dependencies of dependencies are not picked up

### ISSUE THREAD

**Issue by allanbowe** [macropeople/sasjs-cli#24]
scenario:

* service calls a macro from macro folder
* macro calls another macro from macro folder
* that macro calls a macro from the macrocore library

^^ this last dependency is not picked up.

**Comment by krishna-acondy** [comment]
@allanbowe This is working and tested in https://github.com/macropeople/sasjs-cli/blob/master/test/getDependencyPaths.spec.js
