### ISSUE TITLE
sasjs command should autodetect home directory

### ISSUE THREAD

**Issue by allanbowe** [macropeople/sasjs-cli#88]
If a `/sasjs/sasjsconfig.json` file is not found, the `sasjs` command should `cd ..` until hitting root, or finding the config file.

![image](https://user-images.githubusercontent.com/4420615/79124826-6d946280-7d9d-11ea-92cc-e2172c897bc8.png)

**Comment by saadjutt01** [comment]
It will check for following commands,
"compile"
"build"
"deploy"
"db"
"compilebuild"
"compilebuilddeploy"
"web"

sets project home, 
if not found displays message and stop executing.
